### PR TITLE
Added Dracula Theme

### PR DESCRIPTION
**Pull request by rpoovey**
Using the Solarized-community css as a template I converted it to use Dracula color palette.

### CODE REVIEW

**Comment by mihakralj** [comment]
just for fun, try this color theme that I use (it is Dracula Pro based):

@charset "UTF-8";
:root {
--base03: #1a182f;
--base02: #252239;
--base01: #534f63;
--base00: #6b6879;
--base0: #84818f;
--base1: #9f9ca6;
--base2: #d5d3d7;
--base3: #e2e2dc;

--accent:#278bd3;

--red:    #dc312e;
--green:  #859900;
--yellow: #b58900;
--orange: #e55800;
--magenta:#d33682;
--violet: #6c71c4;
--blue:   #278bd3;
--cyan:   #2aa198;
--fwblock:  #bb5a4830;
--fwpass:  #008b0d30;
}

**Comment by rpoovey** [comment]
They both look great. Maybe add a couple options for pro base/free based and varying accent colors? I think the dracula orange looks great for accent as well.

**Comment by mihakralj** [comment]
How about you make a PR to Solarized theme and add all your (great!) changes, plus add your Color.css (with a different name) to the css folder.

I have half-finished Volt page that allows picking any file in css folder and copy it to colors.css.

Plus the ability to customize all 17 colors.

If you would prefer to keep ypur fork, I am totally ok too! 😊

**Comment by mihakralj** [comment]
The theme switcher doesn't work anymore? You should fix it - or remove the jquery for the button:
image

**Review by mihakralj — CHANGES_REQUESTED** [review]
If you created dark-only theme (with no light reverse scheme), you should clean-up several files and jquery code to remove the switching logic.

Or, (preferably) make the theme dark/light switchable.

**Comment by rpoovey** [comment]
I didn't even notice that button; was that added to the Solarized theme? I made these adjustments in like 2 hours. Technically the theme switcher does work, I just set both light and dark to the same color settings. Because Dracula :D . I'll clean up the code a bit then.

**Comment by mihakralj** [comment]
The jquery injection of the light/dark  switch is in the theme .js file.

**Comment by rpoovey** [comment]
I deleted the entire theme.js folder and lines 7767-7819 in main.css. 

Refactored the vars to make more logical sense for only having a dark theme. 

But, the checkbox is still present, only without the nice rounded toggle. Any idea? I don't see any other instance of the theme switch in main.css.

Screen Shot 2021-05-26 at 10 32 42 AM

**Comment by mihakralj** [comment]
Just checking that you did the proper reset of GUI?
I have an (overkill) compound command that makes sure everything is reset:
`sudo service configd restart && sudo configctl webgui restart && sudo /usr/local/etc/rc.configure_plugins`

**Comment by mihakralj** [comment]
the checkbox injection is in theme.js; if you deleted it, your GUI is using the cached version:
image

**Comment by rpoovey** [comment]
I ran your command, and still the same behavior. 

I clear cache before every reload after copying the edits. Safari and Firefox have the same behavior. Private browser as well.

**Comment by rpoovey** [comment]
If I delete the highlighted `<span class="navbar-theme" id="theme_toggle">` in the Firefox inspector the check box removes until a refresh. I just cant find where that's getting added in from the main.css

Screen Shot 2021-05-26 at 10 44 54 AM

**Comment by mihakralj** [comment]
it is NOT in the main.css. It is injected from theme.js. Guaranteed. :-)

**Comment by rpoovey** [comment]
You were totally right. I had my scp copy command wrong and it copied the contents not the folder. So the js folder was still there in OPNSense filesystem. Removed folder and its displaying properly.

**Comment by rpoovey** [comment]
Added js folder back in, but removed the theme switch code. Turns out this file also handled icons on the left side bar.

**Comment by mihakralj** [comment]
...it handles icons only if you decided to keep the new FontAwesome that is part of Solarized theme. :-)

**Comment by rpoovey** [comment]
Yeah, I have no reason to change that. I think this is done now and ready for merge if desired.

**Comment by mimugmail** [comment]
Sorry, I'm on vacation for another week and not that often at a computer.

**Review by mimugmail — APPROVED** [review]

**Comment by mimugmail** [comment]
Looks really nice :) Reminds me on MTG https://magic.wizards.com/en/story/planeswalkers/liliana-vess

**Comment by mimugmail** [comment]
It's now available via the repo, thank you guys:
https://www.reddit.com/r/OPNsenseFirewall/comments/npmcer/new_theme_added_to_community_repo_dracula_theme/

**Pull request merged**
