### PR TITLE
Restored file and corrected some icons not displaying

### PR DESCRIPTION
**Pull request by rpoovey**
I think in my testing/comparing the `main.css` from Solarized to Dracula I deleted the `main.css` file in Solarized folder. This is just a push to restore that.

@mihakralj You might double check its contents? I just pulled it from your previous commit.

Also with the help of mihakralj I corrected some icons not displaying properly in Dracula. I have found a couple more but wanted to get this pushed back up for the file restore.

### CODE REVIEW

**Comment by mimugmail** [comment]
@mihakralj OK for you?

**Comment by mihakralj** [comment]
Perfect! 👍

**Comment by rpoovey** [comment]
Finally found some time to correct all the missing icons that I have come across in the Dracula theme.

**Comment by erlendk** [comment]
This should probably have been split into two PRs, but anyways: Wanted to try out the Solarized theme, but it is broken, and it seems that (a part of) this PR would fix it.

**Comment by mimugmail** [comment]
I will build the plugins the next days :)

**Comment by mimugmail** [comment]
@rpoovey @erlendk I updated the repo, give it try :)

**Comment by rpoovey** [comment]
@mimugmail I just tested, something doesnt seem right. Hopefully its just me. @mihakralj, can you verify the contents of `main.css` / solarized theme?

**Comment by erlendk** [comment]
@mimugmail Tested it now, and it is loading the main.css. Looks quite good to me, although I don't know how it has been looking before. The light version is definitely easier on the eyes than the default theme. The room I am sitting in now is a little bit too light for evaluating the dark version.

What I can say is that there is at least one place missing some icons:
Screenshot from 2022-05-03 19-38-21

Compared to the default theme:
Screenshot from 2022-05-03 19-42-33

I am quite new to OPNsense, so I might not notice problems that more seasoned users would notice.

What problems are you experiencing @rpoovey?

**Comment by mihakralj** [comment]
missing icons: if I remember correctly, HTML is pulling icons from two different sets: from FontAwesome and from <something I can't remember>. When I was cleaning the stylesheet, I removed the reference to the other CSS with icons (and only used FontAwesome icons). Clearly didn't work well. :-)

We can make couple of aliases in css to use FontAwesome icons for all broken images.

Colors: Solarized is a specific color scheme that allows you to flip from dark to light without any other changes. If you change one color, you break the scheme/model. See more here: https://ethanschoonover.com/solarized/

**Comment by rpoovey** [comment]
I'm gonna move this conversation to the issue thread. Since this is a closed PR.

**Pull request merged**
