### PR TITLE
Solarized color scheme + bright/dark toggle switch

### PR DESCRIPTION
**Pull request by mihakralj**
I am using this color theme for a while - and with its easy toggle between light and dark it is a charm to work with.

### CODE REVIEW

**Review by mimugmail — APPROVED** [review]
I pull it in and give it a test, thx :)

**Comment by mimugmail** [comment]
I like the dark one, but when I switch to dark with every click I got every page presented in bright for a microsecond.
Any chance to fix this? Or make a second theme?

**Comment by mihakralj** [comment]
It is a long path on each page load: page is generated and rendered (bright), the theme.js kicks in, injects the switch into the page, reads the stored preference and then flips the color theme defined in color.css

I could write an api to physically flip the color.css and prevent the white-to-dark flip in real time as done now.

I cannot see any other way without touching OPNSenese core files.

**Comment by mimugmail** [comment]
And why not building 2 separate themes without switching?

**Comment by mihakralj** [comment]
I work in a sunroom (glass house). Dark theme during the day is terrible due to the sunlight. The bright theme during the evening/night hours is even more terrible. I *love* apps and sites where I can flip bright/dark at will, depending on the time of the day...

Let me find a compromise this weekend - I have an idea.

**Pull request merged**
